const
FULL_ARC = Math.PI * 2,
DEG      = Math.PI / 180,
RAD_30   = Math.PI / 6,
RAD_60   = Math.PI / 3,
RAD_90   = Math.PI / 2,
SQRT_3   = Math.sqrt(3),
SIN_60   = SQRT_3 / 2,

SATURATION_GRADIENT_Y_MULTIPLIER = SQRT_3 / 4;

export { FULL_ARC, DEG, RAD_30, RAD_60, RAD_90, SQRT_3, SIN_60, SATURATION_GRADIENT_Y_MULTIPLIER }
